name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Linter
        run: python -m py_compile main.py

  train:
    runs-on: ubuntu-latest
    needs: linter

    # شرط تشغيل train (Gatekeeper)
    if: github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[run-train]')

    steps:
      - uses: actions/checkout@v3

      - name: Train Model
        run: |
          echo "Training started..."
          exit 1   # simulate failure

      - name: Create Error Log (only if failed)
        if: failure()
        run: |
          echo "Training failed! Check logs." > error_logs.txt

      - name: Upload Error Log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-logs
          path: error_logs.txt

      - name: Cleanup (always run)
        if: always()
        run: echo "Cleaning up temporary cloud volumes..."
